# GenVersion.cmake
# Runs `git describe --tags --always --dirty --match 'v*'` and writes two files:
#   - ${OUT_HEADER}   : C++ header defining AV_VERSION / AV_VERSION_FULL
#   - ${OUT_TYPST}    : Typst snippet defining AV_VERSION / AV_VERSION_DATE
#
# Expected -D variables:
#   SOURCE_DIR   : repo root (where git lives)
#   OUT_HEADER   : e.g. build/generated/version.h
#   OUT_TYPST    : e.g. doc_typst/_version.typ
#   FALLBACK     : fallback version string if git fails (e.g. "v0.22")

if(NOT DEFINED SOURCE_DIR OR NOT DEFINED OUT_HEADER OR NOT DEFINED OUT_TYPST OR NOT DEFINED FALLBACK)
    message(FATAL_ERROR "GenVersion: missing -D SOURCE_DIR / OUT_HEADER / OUT_TYPST / FALLBACK")
endif()

find_package(Git QUIET)

set(GIT_VERSION "${FALLBACK}")
set(GIT_DATE    "")

if(Git_FOUND)
    execute_process(
        COMMAND ${GIT_EXECUTABLE} describe --tags --always --dirty --match "v*"
        WORKING_DIRECTORY ${SOURCE_DIR}
        OUTPUT_VARIABLE DESC
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
        RESULT_VARIABLE RC
    )
    if(RC EQUAL 0 AND NOT "${DESC}" STREQUAL "")
        set(GIT_VERSION "${DESC}")
    endif()

    execute_process(
        COMMAND ${GIT_EXECUTABLE} log -1 --format=%cs
        WORKING_DIRECTORY ${SOURCE_DIR}
        OUTPUT_VARIABLE GIT_DATE
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
    )
endif()

if("${GIT_DATE}" STREQUAL "")
    string(TIMESTAMP GIT_DATE "%Y-%m-%d")
endif()

# Short form: strip leading 'v' and any "-N-gHASH" suffix for CLI (e.g. "0.22").
string(REGEX REPLACE "^v" "" SHORT_VERSION "${GIT_VERSION}")
string(REGEX REPLACE "-.*$" "" SHORT_VERSION "${SHORT_VERSION}")

# ── C++ header ────────────────────────────────────────────────────────────────
set(HEADER_CONTENT "// Auto-generated by cmake/GenVersion.cmake — do not edit by hand.
#pragma once

#define AV_VERSION       \"${SHORT_VERSION}\"     // e.g. \"0.22\"
#define AV_VERSION_FULL  \"${GIT_VERSION}\"       // e.g. \"v0.22-3-gabc1234-dirty\"
#define AV_VERSION_DATE  \"${GIT_DATE}\"          // e.g. \"2026-04-23\"
")

# Write only if content changed (avoids unnecessary rebuilds).
set(WRITE_HEADER TRUE)
if(EXISTS "${OUT_HEADER}")
    file(READ "${OUT_HEADER}" OLD)
    if("${OLD}" STREQUAL "${HEADER_CONTENT}")
        set(WRITE_HEADER FALSE)
    endif()
endif()
if(WRITE_HEADER)
    file(WRITE "${OUT_HEADER}" "${HEADER_CONTENT}")
    message(STATUS "GenVersion: wrote ${OUT_HEADER} (${GIT_VERSION} @ ${GIT_DATE})")
endif()

# ── Typst snippet ─────────────────────────────────────────────────────────────
set(TYPST_CONTENT "// Auto-generated by cmake/GenVersion.cmake — do not edit by hand.
#let AV_VERSION = \"${GIT_VERSION}\"
#let AV_VERSION_SHORT = \"${SHORT_VERSION}\"
#let AV_VERSION_DATE = \"${GIT_DATE}\"
")

set(WRITE_TYPST TRUE)
if(EXISTS "${OUT_TYPST}")
    file(READ "${OUT_TYPST}" OLD)
    if("${OLD}" STREQUAL "${TYPST_CONTENT}")
        set(WRITE_TYPST FALSE)
    endif()
endif()
if(WRITE_TYPST)
    file(WRITE "${OUT_TYPST}" "${TYPST_CONTENT}")
    message(STATUS "GenVersion: wrote ${OUT_TYPST}")
endif()
